language:
 - java

sudo: required

services:
  - docker

jdk:
 - oraclejdk8

os: 
  - linux

script:
  - cd rewayaat
  - mvn package docker:build cobertura:cobertura
  - cd ..
  - chmod a+x deploy.sh ecs_deploy.sh
  - ./deploy.sh

notifications: # set notification options
  email:
    recipients:
      - rewayaat.org@gmail.com
    # change is when the repo status goes from pass to fail or vice versa
    on_success: change
    on_failure: always
after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api-key: $OAUTH_TOKEN
  file_glob: true
  file: "rewayaat/target/rewayaat-*.jar"
  skip_cleanup: true
  on:
    tags: true
